### PR TITLE
Vep

### PR DESCRIPTION
**Pull request by illusional**
Adding Vep to Janis-bioinf. This is a bit complicated and may require some rework for plugins.

### CODE REVIEW

**Comment by matthdsm** [comment]
Quick question,

Why not make your life easier and use the bioconda version of VEP + container?
All plugins are already included there and the docker image is pre made.

Cheers
M

**Comment by illusional** [comment]
Thanks @matthdsm, that's exactly what I was looking for!

I think this will need some extra features to janis-core to ensure correct binding of plugin dependencies while creating the command line, but the bioconda docker is exactly what I wanted, and you built it!

**Comment by matthdsm** [comment]
conda has images for virtually every piece of software registered there, so it's an easy to use resource (cfr my PR, also conda dockers).

Cheers
M

**Comment by illusional** [comment]
Yeah agreed, my first port of call is usually the original vendor for a container, and then biocontainers. But the biocontainers is definitely more what we want here.

**Comment by illusional** [comment]
So the plugins have always been a bit of a complication, but now with expressions (https://github.com/PMCC-BioinformaticsCore/janis-core/pull/10/files), we're one step closer to this being merged.

The syntax for a plugin looks like the following:

```python
ToolArgument(
    If(
        IsDefined(InputSelector("caddReference")),
        [
            "--plugin",
            "CADD," + JoinOperator(InputSelector("caddReference"), ","),
        ],
        None,
    )
),
```

I'm waiting on clarifying the WDL separator function (and obviously the PR expression to merge) and then I can test this a bit more.

The reality is every plugin effectively needs to be added to the wrapper separately, not a big deal but something to keep in mind. I've added one (1) thing for a custom plugin, that block could be duplicated but is a little hard to make generic (feedback welcome)!

**Comment by illusional** [comment]
This requires https://github.com/PMCC-BioinformaticsCore/janis-core/pull/10 to be completed before this can be merged.

**Comment by illusional** [comment]
@rlupat this is probably ready to merge with janis-core changes already in master and released.

**Pull request merged**
