### PR TITLE
WIP - new tool: bcl2fastq

### PR DESCRIPTION
**Pull request by matthdsm**
In progress
It seems the illumina tools use a slightly other mechanism to register than the other tools, but other than that, ready to go IMO.

Cheers
M

### CODE REVIEW

**Comment by matthdsm** [comment]
I don't seem to get the module registered for import. Am I missing something here?
M

**Comment by illusional** [comment]
Hey @matthdsm, not sure how this slipped through my radar. You just need to add:

```python
from .bcl2fastq.versions import Bcl2Fastq_2_20_0, Bcl2FastqLatest
```

to [`janis_bioinformatics/tools/illumina/__init__.py`](https://github.com/PMCC-BioinformaticsCore/janis-bioinformatics/blob/master/janis_bioinformatics/tools/illumina/__init__.py) and it should work all fine (did in my test at least).

**Comment by matthdsm** [comment]
Should have found that on my own!
Anyway, fixed it, so this PR should be good to merge.
If you have any comments, let me know!

Cheers
M

**Comment by illusional** [comment]
Hey @matthdsm, thanks for being patient with this PR. I wanted to have a better mechanism for overriding container before I merged this. After some thought I've added `container_override` to the translate methods and an equivalent to the CLI.

I've got a few things left to complete before I merge this in, but wanted to keep you updated.

**Comment by matthdsm** [comment]
Great to hear it's not forgotten!
Thanks for the update.

**Comment by illusional** [comment]
Hi @matthdsm, I've merged the related branch in. If you're happy with this PR I'm happy to merge it in now.

**Comment by matthdsm** [comment]
Hi Michael,
Great! I suppose this PR is ready to merge. 
It's been a while since I've done any workflow work, so I might do some additional PR's when I'm back on this.
In the mean time, let's spread the joy and let the community have this!

cheers
M

**Comment by illusional** [comment]
Thanks for your contribution @matthdsm, you can find the docs here: https://janis.readthedocs.io/en/latest/tools/bioinformatics/illumina/bcl2fastq.html

There are instructions for overriding the container which are available in [`v0.9.16`](https://github.com/PMCC-BioinformaticsCore/janis-assistant/releases/tag/v0.9.16).

**Pull request merged**
