### PR TITLE
Oncopipe variant calling update

### PR DESCRIPTION
**Pull request by jiaan-yu**
Hi Michael,
I've updated the branch with oncopipe variant calling section.
'master' and '0.11x' branch have merged into this branch as well.
No unit tests are included yet.
Thanks,
Jiaan

### CODE REVIEW

**Comment by illusional** [comment]
Hey @jiaan-yu, I've fixed the PMCC-BioinfCore bioinformatics oncopipe branch, do you mind just just looking over the new (actual) change-list to make sure you're happy. Otherwise this looks good to me.

**Comment by jiaan-yu** [comment]
Hi @rlupat and @junyk 
The update on oncopipe branch is ready. It includes star alignment, arriba fusion calling, and gatk variant calling.
The summary of the changes:
- Add several new tools in arriba
- Clean up oncopipe: Add two new scripts, per sample workflow "oncopipeSample.py" and per run workflow "oncopipe.py". And remove redundant scripts "star.py" and "variants.py".
- Other minor changes on tools.
Thanks,
Jiaan

**Comment by rlupat** [comment]
hi @jiaan-yu - there are a few conflicts that needs to be resolved before your branch can be merged. 
Do you mind taking another look at this PR?

**Comment by jiaan-yu** [comment]
Conflicts solved after merging with oncopipe and master branch of the main repo.

**Pull request merged**
