### PR TITLE
Remove split bam step from gatk calling

### PR DESCRIPTION
**Pull request by jiaan-yu**
I remove the split bam step from the GATK variant calling.
All the tools can perform variant calling on a given interval, so there is no need to split the bams into chromosomes beforehand.

### CODE REVIEW

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Comment by jiaan-yu** [comment]
@janis-bot

**Pull request closed without merging**
