### PR TITLE
Unit test wgssomatic

### PR DESCRIPTION
**Pull request by xinzhel97**
Add unit tests to tools involved in WGSSomaticGATK pipeline, except the ones that were already covered in WGSGermlineGATK pipeline

### CODE REVIEW

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Comment by rlupat** [comment]
Hi @junyk and @xinzhel97 - some of the test_data files are included as part of this PR. Just checking, if they are intended to be checked in to this repo? 

Thanks

**Comment by junyk** [comment]
@rlupat @xinzhel97 i think we prefer to upload them to Nectar. Including expected files. Especially if they are big.

**Comment by xinzhel97** [comment]
It's only a temporary solution because the files are not up on Nectar yet. It's also what we did last time. Once the files are uploaded, they can be removed and I'll also change the file paths in unit tests.

**Review by junyk — CHANGES_REQUESTED** [review]
Just leaving a note here so we don't forget. As per discussion on Wednesday, we want to move all the local test files to Nectar. So, we will need to update the file path in this PR to nectar URL. Thanks!

**Comment by xinzhel97** [comment]
@junyk I just updated the file paths and deleted the local testing files. Hope that helps

**Review by junyk — COMMENTED** [review]
@janis-bot

**Review by junyk — COMMENTED** [review]
@janis-bot

**Pull request merged**
